name: CI (Intel)

on:
  workflow_call:

jobs:
  build-and-test-intel:
    name: Intel Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y cmake make wget g++ gfortran libnetcdf-dev libnetcdff-dev liblapack-dev libopenblas-dev

      - name: Install Intel compilers & MPI
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with:
          install-mpi: true
          mpi-wrapper-setup: oneapi
          env-update: true

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v5
        with:
          path: |
            spack-stack
            ~/.spack
          key: spack-${{ runner.os }}-${{ env.cache_key }}

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/JCSDA/spack-stack
          cd spack-stack
          git checkout 37c009d
          git submodule update --init --recursive
          . ./setup.sh

          spack mirror add emc-common-build-cache oci://ghcr.io/NOAA-EMC/ci-common-build-cache-oneapi
          wget https://github.com/NOAA-EMC/ci-common-build-cache/releases/download/may2026-signing-key/spack-signing-public.asc
          spack gpg trust spack-signing-public.asc

          spack env create catchem-env
          spack env activate catchem-env

          spack compiler find
          spack external find

          spack config add "packages:esmf:require:^openmpi"
          spack config add "packages:all:compiler:[oneapi]"
          spack add esmf yaml-cpp parallelio+pnetcdf py-pip

          spack concretize
          spack install -v --fail-fast --dirty
          spack gc -y
          spack clean --all

      - name: Configure
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate catchem-env
          mkdir build && cd build
          cmake .. \
            -DCATCHEM_BUILD_TESTING=ON \
            -DCATCHEM_BUILD_NUOPC=ON \
            -DBUILD_MUSICA=ON \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build build -j2

      - name: Test
        run: |
          ctest --test-dir build --output-on-failure
