name: Main CI/CD

on:
  push:
#    branches: [main, develop]
    branches: [feature/container-build]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  ci-gnu:
    uses: ./.github/workflows/build-and-test.yml

  ci-spack:
    uses: ./.github/workflows/spack-stack.yml

  docker-develop:
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  release:
    needs: [lint, ci-gnu, ci-spack, docker-develop]
#    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/container-build'
    uses: ./.github/workflows/semantic-release.yml

  docs:
    needs: [lint, ci-gnu, ci-spack, docker-develop, release]
    uses: ./.github/workflows/docs.yml
