name: Main CI/CD

on:
  push:
#    branches: [main, develop]
    branches: [feature/container-build]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  lint:
    uses: ./.github/workflows/lint.yml

  ci-gnu:
    uses: ./.github/workflows/build-and-test.yml

  ci-spack:
    uses: ./.github/workflows/spack-stack.yml

  docker-develop:
    needs: [setup]
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ needs.setup.outputs.short_sha }}
      cache_tag: ${{ needs.setup.outputs.short_sha }}
      is_release: false
      base_project_name: catchem-spack-base-dev
      project_name: catchem-dev
    secrets: inherit

  release:
    needs: [lint, ci-gnu, ci-spack, docker-develop]
    if: github.event_name == 'push'
    uses: ./.github/workflows/semantic-release.yml
    secrets: inherit

  debug-release-outputs:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Echo Release Outputs
        run: |
          echo "New release published: ${{ needs.release.outputs.new_release_published }}"
          echo "New release version: ${{ needs.release.outputs.new_release_version }}"

  docker-release:
    needs: [release, setup]
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ needs.release.outputs.new_release_version }}
      cache_tag: ${{ needs.setup.outputs.short_sha }}
      is_release: true
      base_project_name: catchem-spack-base
      project_name: catchem
    secrets: inherit

  docs:
    needs: [lint, ci-gnu, ci-spack, release, docker-develop, docker-release]
    if: |
      always() &&
      needs.lint.result == 'success' &&
      needs.ci-gnu.result == 'success' &&
      needs.ci-spack.result == 'success' &&
      needs.docker-develop.result == 'success' &&
      (needs.release.result == 'success' || needs.release.result == 'skipped') &&
      (needs.docker-release.result == 'success' || needs.docker-release.result == 'skipped')
    uses: ./.github/workflows/docs.yml
